# Numpy

- Numpy stands for Numerical Python
- list are slow numpy are fast beacuse of fixed type faster to read less bytes of memory.
- no type checking 
- it implies contiguous memory

# Applications

- Mathematics(MATLAB replacement)
- Plotting (Matplotlib)
- Backend (pandas,digital photography)
- Machine Learning 



In [3]:
import numpy as np

In [4]:
l=[1,2,3,4,5]
array.l

NameError: name 'array' is not defined

In [3]:
len(dir(np))

618

### Basics

In [62]:
a=np.array([[1,2,3,4],[5,6,7,8]],dtype='int32')

In [49]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


# get the dimension of numpy array

In [53]:
a.ndim

2

In [55]:
#Get Shape
a.shape

(2, 4)

In [63]:
#Get type
a.dtype

dtype('int32')

In [64]:
#Get size of element
#if dtype=int16=size=2bytes 
#dtype=int32=size=4bytes 
a.itemsize

4

In [69]:
#Get total size  a.nbytes=a.size*a.itemsize 
a.nbytes

32

# Acceseing elements rows and columns

In [8]:
b=np.array([[9,2,3,4,5,6,7],[3,4,5,6,7,8,9]])
print(b)

[[9 2 3 4 5 6 7]
 [3 4 5 6 7 8 9]]


In [9]:
b.shape

(2, 7)

In [11]:
np.sort(b, axis=1)

array([[2, 3, 4, 5, 6, 7, 9],
       [3, 4, 5, 6, 7, 8, 9]])

In [2]:
import numpy as np

a = np.array([[1,2,3],[0,1,4]])

print (a.ndim)

2


In [79]:
#get a specific element
b[1, -2]

8

In [81]:
#geta specific row
b[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [82]:
#geta specific column
b[:,4]

array([5, 7])

In [90]:
#slicing
b[1,1:6:2]

array([4, 6, 8])

In [92]:
b[1,5]=20
print(b)

[[ 1  2  3  4  5  6  7]
 [ 3  4  5  6  7 20  9]]


In [96]:
b[:,2]=[1,2]
print(b)

[[ 1  2  1  4  5  6  7]
 [ 3  4  2  6  7 20  9]]


In [103]:
c=np.array([[[1,2],[3,4]],[[4,5],[5,6]]],dtype='int16')

In [104]:
print(c)

[[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]


In [111]:
c[:,0,:]=[[9,9],[8,8]]

In [112]:
print(c)

[[[9 9]
  [3 4]]

 [[8 8]
  [5 6]]]


# Initializing different types of array

In [116]:
##All zeros array
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [118]:
#all ones matrix
np.ones((2,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [119]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [122]:
np.full_like(a,4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [123]:
np.random.rand(4,2)

array([[0.62134913, 0.62256625],
       [0.33607606, 0.8539169 ],
       [0.97500224, 0.46802388],
       [0.07700992, 0.52366492]])

In [130]:
np.random.randint(2,5, size=(3,3))

array([[3, 2, 3],
       [4, 2, 3],
       [3, 4, 3]])

In [132]:
np.identity(4,dtype='int32')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [139]:
arr=np.array([[1,2,3]])
r=np.repeat(arr,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [13]:
output= np.ones((5,5),dtype='int32')
#print(output)
z= np.zeros((3,3))
#print(z)
z[1,1]=9
# print(z)
output[1:-1,1:-1]=z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [151]:
####for copying values we should not use as a=b instead we should use .copy() method as
c=np.array([3,6,9,12,15,18])
d=c.copy()
d[1]=30
print(c,d)


[ 3  6  9 12 15 18] [ 3 30  9 12 15 18]


# Mathematics

In [152]:
print(c)

[ 3  6  9 12 15 18]


In [157]:
print(c+5)
print(c-5)
print(c*5)
d=np.array([4,5,6,7,8,9])
print(c+d)
c**2


[ 8 11 14 17 20 23]
[-2  1  4  7 10 13]
[15 30 45 60 75 90]
[ 7 11 15 19 23 27]


array([  9,  36,  81, 144, 225, 324], dtype=int32)

In [162]:
print(np.sin(90))

0.8939966636005579


# linear Algebra

In [167]:
a=np.full((2,3),4)
print(a)
b=np.ones((3,3))
print(b)

np.matmul(a,b)

[[4 4 4]
 [4 4 4]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[12., 12., 12.],
       [12., 12., 12.]])

In [168]:
c= np.identity(3)
np.linalg.det(c)

1.0

In [169]:
###Statistics

In [170]:
s=np.array([[1,2,3,4],[4,5,6,7]])
print(s)

[[1 2 3 4]
 [4 5 6 7]]


In [172]:
np.min(s,axis=0)

array([1, 4])

In [174]:
np.max(s,axis=1)

array([4, 7])

In [175]:
np.sum(s,axis=0)

array([ 5,  7,  9, 11])

In [176]:
####Recognizing arrays

In [180]:
print(s.reshape(2,2,2))

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [183]:
#Vertical statcking
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [184]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.hstack([v1,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

In [ ]:
###Load data from file
filedata= np.genfromtxt("name of txt file",delimiter=',')
filedata.astype('int32')  #to chnage the type of data to integer

In [ ]:
#####Bolien masking and advance indexing

In [ ]:
filedata[filedata>50] # only provide indexing to those numbers which are greater than 50

In [ ]:
##Indexing wth a list in numpy

In [185]:
h=np.array([1,2,3,4,5,6,7,8,9])
h[[1,2,8]]


array([2, 3, 9])

In [189]:
np.all(h>5,axis=0)   ##repalce h with filedata

False

## Write a universal function which return true if a no. is even

In [1]:
def even(n):
    if n%2==0:
        return 1
    else:
        return 0

In [4]:
import numpy as np

### Universal function ufunc using
- np.frompyfunc(function name,no. of input,no. of output)

In [5]:
A=np.arange(1,11)
fun = np.frompyfunc(even,1,1)
fun(A)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=object)

In [6]:
type(fun)

numpy.ufunc

In [7]:
def age(i,f):
    return f-i

### Searching arrays
- to find the index of that value

In [8]:
b= np.array([4,6,8,2,3,5,7,8])

In [9]:
np.where(b==8)

(array([2, 7], dtype=int32),)

## Sorting
- complexity is O(NlogN)

In [11]:
np.sort(b)

array([2, 3, 4, 5, 6, 7, 8, 8])

In [13]:
C = np.random.randint(10,50,(5,4))

In [14]:
print(C)

[[22 14 43 34]
 [37 24 30 35]
 [31 41 22 44]
 [25 10 32 48]
 [10 36 38 32]]


In [16]:
np.sort(C,axis=0)

array([[10, 10, 22, 32],
       [22, 14, 30, 34],
       [25, 24, 32, 35],
       [31, 36, 38, 44],
       [37, 41, 43, 48]])

In [18]:
np.sort(C[:,[2]],axis=0)

array([[22],
       [30],
       [32],
       [38],
       [43]])